# Generated by Django 5.2.14 on 2026-05-19 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0003_producto_precio_usd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEspecificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.CharField(blank=True, max_length=100, null=True)),
                ('chipset', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_ram', models.CharField(blank=True, max_length=100, null=True)),
                ('vram', models.CharField(blank=True, max_length=100, null=True)),
                ('watts', models.CharField(blank=True, max_length=100, null=True)),
                ('velocidad_ram', models.CharField(blank=True, max_length=100, null=True)),
                ('almacenamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('pci', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
    ]
