# Generated by Django 5.2.14 on 2026-06-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoEspecificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoespecificacion',
            options={'verbose_name': 'Especificación de Producto', 'verbose_name_plural': 'Especificaciones de Productos'},
        ),
        migrations.AlterModelTable(
            name='productoespecificacion',
            table='productoEspecificacion',
        ),
    ]
