# Generated by Django 5.2.14 on 2026-05-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
