# Generated by Django 5.2.14 on 2026-06-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_producto_precio_usd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='marca_id',
            new_name='marca',
        ),
    ]
