# Generated by Django 5.2.15 on 2026-07-05 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalleCompra', '0002_rename_compra_id_detallecompra_compra_and_more'),
        ('detalleVenta', '0002_rename_producto_id_detalleventa_producto_and_more'),
        ('producto', '0009_alter_producto_categoria'),
        ('proveedor', '0002_alter_proveedor_nombre_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id_lote', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de Entrada')),
                ('cantidad_inicial', models.IntegerField(verbose_name='Cantidad Inicial')),
                ('cantidad_disponible', models.IntegerField(verbose_name='Cantidad Disponible')),
                ('precio_costo_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (USD)')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detalle_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lote', to='detalleCompra.detallecompra', verbose_name='Detalle de Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='producto.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Lote de Producto',
                'verbose_name_plural': 'Lotes de Productos',
                'db_table': 'lote_producto',
                'ordering': ['fecha_entrada', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoteConsumo',
            fields=[
                ('id_consumo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad Consumida')),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Consumo')),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_lote', to='detalleVenta.detalleventa', verbose_name='Detalle de Venta')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='lote.loteproducto', verbose_name='Lote')),
            ],
            options={
                'verbose_name': 'Consumo de Lote',
                'verbose_name_plural': 'Consumos de Lotes',
                'db_table': 'lote_consumo',
                'ordering': ['-fecha_consumo'],
            },
        ),
    ]
