# Generated by Django 5.2.13 on 2026-06-28 23:50

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0009_alter_producto_categoria'),
        ('usuario', '0002_alter_usuario_apellido_alter_usuario_ci_and_more'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id_conversacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'db_table': 'conversacion',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='agenteConversacional.conversacion')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'conversacion_mensaje',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductoEmbedding',
            fields=[
                ('id_embedding', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('vector', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='producto.producto')),
            ],
            options={
                'verbose_name': 'Embedding de Producto',
                'verbose_name_plural': 'Embeddings de Productos',
                'db_table': 'producto_embedding',
            },
        ),
    ]
