# Generated by Django 5.2.15 on 2026-07-01 21:19

import pgvector.django.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenteConversacional', '0001_initial'),
        ('producto', '0009_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='productoembedding',
            index=pgvector.django.indexes.HnswIndex(fields=['vector'], name='vector_cos_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
