# Generated by Django 5.2.15 on 2026-07-13 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenteConversacional', '0002_alter_mensaje_created_at_and_more'),
        ('usuario', '0002_alter_usuario_apellido_alter_usuario_ci_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaHerramienta',
            fields=[
                ('id_auditoria', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=20)),
                ('herramienta', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('operacion', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_resultados', models.IntegerField(default=0)),
                ('estado', models.CharField(max_length=20)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('duracion', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_herramienta', to='agenteConversacional.conversacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_herramienta', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría de Herramienta',
                'verbose_name_plural': 'Auditorías de Herramientas',
                'db_table': 'auditoria_herramienta',
            },
        ),
    ]
