# Generated by Django 5.2.15 on 2026-07-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenteConversacional', '0003_auditoriaherramienta'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriaherramienta',
            name='nivel_riesgo',
            field=models.CharField(default='BAJO', max_length=10),
        ),
    ]
