# Generated by Django 5.2.13 on 2026-04-21 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detalleCompra', '0001_initial'),
        ('detalleVenta', '0001_initial'),
        ('producto', '0001_initial'),
        ('tipoMovimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.IntegerField()),
                ('stock_actual', models.IntegerField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detalleCompra_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detalleCompra.detallecompra')),
                ('detalleVenta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='detalleVenta.detalleventa')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('tipoMovimiento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoMovimiento.tipomovimiento')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimiento',
            },
        ),
    ]
