# Generated by Django 5.2.14 on 2026-06-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimiento',
            old_name='detalleCompra_id',
            new_name='detalleCompra',
        ),
        migrations.RenameField(
            model_name='movimiento',
            old_name='detalleVenta_id',
            new_name='detalleVenta',
        ),
        migrations.RenameField(
            model_name='movimiento',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='movimiento',
            old_name='tipoMovimiento_id',
            new_name='tipoMovimiento',
        ),
    ]
