# Generated by Django 5.2.14 on 2026-05-15 19:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras en el apellido')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ci',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Solo se permiten números en el CI')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras en el nombre')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Solo se permiten números en el teléfono')]),
        ),
    ]
