# Generated by Django 5.2.15 on 2026-07-13 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_apellido_alter_usuario_ci_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_ingresado', models.CharField(db_index=True, max_length=150)),
                ('ip_origen', models.GenericIPAddressField(db_index=True)),
                ('cantidad_intentos', models.IntegerField(default=0)),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True)),
                ('ultimo_intento', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intento de Login',
                'verbose_name_plural': 'Intentos de Login',
                'db_table': 'intento_login',
            },
        ),
    ]
