# Generated by Django 5.2.13

from django.db import migrations

def rename_empleado_to_vendedor(apps, schema_editor):
    Rol = apps.get_model('rol', 'Rol')
    # Actualiza el nombre del rol Empleado a Vendedor si existe
    Rol.objects.filter(nombre='Empleado').update(nombre='Vendedor')

def rollback_vendedor_to_empleado(apps, schema_editor):
    Rol = apps.get_model('rol', 'Rol')
    Rol.objects.filter(nombre='Vendedor').update(nombre='Empleado')

class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_empleado_to_vendedor, rollback_vendedor_to_empleado),
    ]
