# Generated by Django 5.2.15 on 2026-07-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detalleCompra', '0002_rename_compra_id_detallecompra_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
