# Generated by Django 5.2.14 on 2026-05-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipoMovimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipomovimiento',
            name='nombre',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=100),
        ),
    ]
