# Generated by Django 5.2.13 on 2026-05-10 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0002_producto_imagen'),
        ('tipoCambio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPrecio',
            fields=[
                ('id_historialPrecio', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('tipo_cambio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipoCambio.tipocambio')),
            ],
            options={
                'verbose_name': 'HistorialPrecio',
                'verbose_name_plural': 'HistorialPrecios',
                'db_table': 'historialPrecio',
            },
        ),
    ]
