# Generated by Django 5.2.14 on 2026-05-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historialPrecio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialprecio',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialprecio',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
