# Generated by Django 5.2.14 on 2026-06-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historialPrecio', '0002_alter_historialprecio_fecha_fin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historialprecio',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='historialprecio',
            old_name='tipo_cambio_id',
            new_name='tipo_cambio',
        ),
    ]
