# Generated by Django 5.2.14 on 2026-06-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detalleVenta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleventa',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='venta_id',
            new_name='venta',
        ),
    ]
