# Generated by Django 5.2.13 on 2026-06-24 05:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0009_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stock_minimo', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('stock_maximo', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Máximo')),
                ('ubicacion', models.CharField(default='Almacén Principal', max_length=150, verbose_name='Ubicación Física')),
                ('fecha_ultimo_inventario', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='producto.producto')),
            ],
            options={
                'verbose_name': 'Inventario de Producto',
                'verbose_name_plural': 'Inventarios de Productos',
                'db_table': 'inventario',
            },
        ),
    ]
