# Generated by Django 5.2.15 on 2026-07-03 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_apellido_alter_cliente_ci_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='passwordCli',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='usuarioCli',
        ),
    ]
