# Generated by Django 5.2.14 on 2026-05-15 19:38

import apps.compra.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(validators=[apps.compra.models.validate_not_past]),
        ),
    ]
