# Generated by Django 5.2.14 on 2026-06-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_alter_compra_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='proveedor_id',
            new_name='proveedor',
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
