# Generated by Django 5.2.15 on 2026-07-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_rename_proveedor_id_compra_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='tipo_cambio_valor',
            field=models.DecimalField(decimal_places=2, default=6.96, max_digits=10),
        ),
    ]
