# Generated by Django 5.2.14 on 2026-06-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_venta_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='cliente_id',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='venta',
            old_name='usuario_id',
            new_name='usuario',
        ),
    ]
