# Generated by Django 5.2.13 on 2026-06-24 04:48

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ0-9\\s\\.\\,\\-\\&]+$', 'Solo se permiten letras, números y caracteres válidos en el nombre')], verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[0-9]+$', 'Solo se permiten números en el NIT')], verbose_name='NIT / Identificación Tributaria')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección Física')),
                ('telefono', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9\\+\\-\\s]+$', 'Solo se permiten números, espacios y los signos + o - en el teléfono')], verbose_name='Teléfono / Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='empresa/', verbose_name='Logo de la Empresa')),
                ('ciudad', models.CharField(default='La Paz', max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Solo se permiten letras en el nombre de la ciudad')], verbose_name='Ciudad/País')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Datos de la Empresa',
                'verbose_name_plural': 'Datos de la Empresa',
                'db_table': 'empresa',
            },
        ),
    ]
