# Generated by Django 5.2.15 on 2026-07-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='google_maps_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace de Google Maps'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True, verbose_name='Longitud'),
        ),
    ]
